import datetime
print("present date and time using():",datetime.datetime.now())
rse=datetime.datetime(2021,9,4,8,8,54,324898)
print("rse:",rse)
print("Long version of year:",rse.strftime("%Y"))
print("Short version of year:",rse.strftime("%y"))
print("=============================================================")
print("Long version of Month:",rse.strftime("%b"))
print("Short version of Month:",rse.strftime("%B"))
print("=============================================================")
print("Long version of Day:",rse.strftime("%a"))
print("Short version of Day:",rse.strftime("%A"))
print("=============================================================")
print("24 Hours Format:",rse.strftime("%H"))
print("12 Hours Format:",rse.strftime("%I"))
#print("AM/PM:",rse.strftime("%P"))
print("=============================================================")
print("Minutes:",rse.strftime("%M"))
print("=============================================================")     
print("Seconds:",rse.strftime("%S"))
print("=============================================================")
print("MicroSeconds:",rse.strftime("%f"))
#%f means date ex:2021-09-04
